on: [push, workflow_dispatch]

permissions:
  id-token: write # needed to integrate with AWS
  contents: read

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3git 
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::1234567890:role/gh-actions-role
          aws-region: eu-west-1
      - name: Install dependencies
        run: npm install -g aws-cdk
      - name: Install required packages
        run: npm i
      - name: Synth stack
        run: cdk synth
      - name: Deploy stack
        run: cdk deploy --all --require-approval never